name = "hopebox"
main = ".output/server/index.mjs"
compatibility_date = "2024-06-01"
workers_dev = true
account_id = "c7817c861c33bda236f1aee1b5139aa3"

[site]
bucket = ".output/public"

[build]
command = "npm run build"